services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DB_NAME=ik_sistemi
      - DB_USER=ik_user
      - DB_PASSWORD=ik_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # db ve redis servisleri aynı kalabilir
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ik_sistemi
      - POSTGRES_USER=ik_user
      - POSTGRES_PASSWORD=ik_password
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  # Celery servislerini geçici olarak kapat
  # celery:
  #   build: .
  #   command: celery -A ik_sistemi worker -l info
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DEBUG=True
  #     - SECRET_KEY=django-insecure-dev-key-change-in-production
  #     - DB_NAME=ik_sistemi
  #     - DB_USER=ik_user
  #     - DB_PASSWORD=ik_password
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #   depends_on:
  #     - db
  #     - redis

  # celery-beat:
  #   build: .
  #   command: celery -A ik_sistemi beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DEBUG=True
  #     - SECRET_KEY=django-insecure-dev-key-change-in-production
  #     - DB_NAME=ik_sistemi
  #     - DB_USER=ik_user
  #     - DB_PASSWORD=ik_password
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:
