# Generated by Django 4.2.7 on 2025-09-29 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdayAkis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aday')),
            ],
        ),
        migrations.CreateModel(
            name='IKFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusteriFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('sektor', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsIlanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('kapanis_tarihi', models.DateTimeField()),
                ('statu', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif')], default='aktif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ik_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ikfirma')),
                ('musteri_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musterifirma')),
            ],
        ),
        migrations.CreateModel(
            name='IsDeneyimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.CharField(max_length=200)),
                ('pozisyon', models.CharField(max_length=200)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_deneyimleri', to='core.aday')),
            ],
        ),
        migrations.CreateModel(
            name='IKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ik_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ikfirma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yetkili_musteri_firmalar', models.ManyToManyField(to='core.musterifirma')),
            ],
        ),
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul', models.CharField(max_length=200)),
                ('bolum', models.CharField(max_length=200)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitimler', to='core.aday')),
            ],
        ),
        migrations.CreateModel(
            name='Aktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivite_tipi', models.CharField(choices=[('telefon', 'Telefon Araması Yapıldı'), ('mail', 'Mail Gönderildi'), ('test', 'Test Gönderildi')], max_length=20)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aday_akis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to='core.adayakis')),
                ('ik_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ikfirma')),
                ('ik_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('statu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statu')),
            ],
        ),
        migrations.AddField(
            model_name='adayakis',
            name='is_ilani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.isilanlari'),
        ),
    ]
